# Generated by Django 4.2.6 on 2023-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=10000, verbose_name='Description')),
                ('image_url', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Image URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
