# Generated by Django 4.2.6 on 2023-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rainbowID',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rainbow User ID'),
        ),
        migrations.AddField(
            model_name='room',
            name='rainbowPassword',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rainbow User Password'),
        ),
    ]
