# Generated by Django 4.2.6 on 2023-10-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Active'),
        ),
    ]
