# Generated by Django 4.2.6 on 2023-10-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_radius', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radcheck',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='radgroupcheck',
            options={'managed': True},
        ),
    ]
