# Generated by Django 4.2.6 on 2023-10-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_radius', '0002_alter_radcheck_options_alter_radgroupcheck_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Radcheck',
        ),
        migrations.DeleteModel(
            name='Radgroupcheck',
        ),
    ]
