# Generated by Django 4.2.6 on 2023-10-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_radius', '0003_delete_radcheck_delete_radgroupcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': True,
            },
        ),
    ]
