# Generated by Django 4.2.6 on 2023-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End date')),
                ('guest', models.IntegerField(blank=True, verbose_name='Guest')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
