# Generated by Django 4.2.6 on 2023-10-31 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('start_date', models.DateField(blank=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, verbose_name='End date')),
                ('guest', models.IntegerField(blank=True, null=True, verbose_name='Guest')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='Days')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('code', models.CharField(blank=True, max_length=200, verbose_name='Reservation Code')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
