# Generated by Django 4.2.6 on 2023-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Guest'),
        ),
    ]
